try 
    purge
end

[cDirThis, cName, cExt] = fileparts(mfilename('fullpath'));
cDirSrc = fullfile(cDirThis, '..', 'src');
cDirMpm = fullfile(cDirThis, '..', 'mpm-packages');

% Add src
addpath(genpath(cDirSrc));
addpath(genpath(cDirMpm));

% Optionally configure with the directory where waveforms are saved
% The default is to use pwd

cDir = fullfile( ...
    cDirThis, ...
    'save' ...
);

dScreenSize = get(0, 'ScreenSize');
        
dWidth = 1250;
dHeight = 700;

hFigure = figure( ...
    'NumberTitle', 'off', ...
    'MenuBar', 'none', ...
    'Name', 'Pupil Fill Test', ...
    'Position', [ ...
        (dScreenSize(3) - dWidth)/2 ...
        (dScreenSize(4) - dHeight)/2 ...
        dWidth ...
        dHeight ...
     ]... % left bottom width height
);
ui = PupilFillGenerator(...
    'cDirWaveforms', cDir ...
);
ui.build(hFigure, 0, 0);
