if exist('purge') > 0
    purge
end

[cDirThis, cName, cExt] = fileparts(mfilename('fullpath'));
cDirSrc = fullfile(cDirThis, '..', 'src');
cDirVendor = fullfile(cDirThis, '..', 'vendor');

% Add src
addpath(genpath(cDirSrc));

% Add dependencies 
addpath(genpath(fullfile(cDirVendor, 'github', 'cnanders', 'matlab-quasar', 'src')));
addpath(genpath(fullfile(cDirVendor, 'github', 'cnanders', 'matlab-gridded-pupil-fill', 'src')));
addpath(genpath(fullfile(cDirVendor, 'github', 'cnanders', 'matlab-instrument-control', 'src')));

% Optionally configure with the directory where waveforms are saved
% The default is to use pwd

cDir = fullfile( ...
    cDirThis, ...
    'save' ...
);

dScreenSize = get(0, 'ScreenSize');
        
dWidth = 1250;
dHeight = 700;

hFigure = figure( ...
    'NumberTitle', 'off', ...
    'MenuBar', 'none', ...
    'Name', 'Pupil Fill Test', ...
    'Position', [ ...
        (dScreenSize(3) - dWidth)/2 ...
        (dScreenSize(4) - dHeight)/2 ...
        dWidth ...
        dHeight ...
     ]... % left bottom width height
);
app = PupilFillGenerator(...
    'cDirWaveforms', cDir ...
);
app.build(hFigure, 0, 0);
